# Item IDs for bait for various monsters.
# If you want to disable taming a certain mob set the code to 0 or adjust permissions.
Bat: 375
Blaze: 369
CaveSpider: 287
Chicken: 295
Cow: 295
Creeper: 318
EnderDragon: 122
Enderman: 381
Ghast: 370
Giant: 41
Golem: 265
MagmaCube: 378
MushroomCow: 40
Pig: 319
PigZombie: 319
Sheep: 338
Silverfish: 280
Skeleton: 352
Slime: 341
SnowMan: 332
Spider: 287
Squid: 349
Villager: 38
VillagerGolem: 265
Witch: 115
Wither: 399
Zombie: 288
# Other options
# If Provokable is true then you are able to hurt your own pet. Your pet will get angry and run away or hurt you.
Provokable: true
# Right click your pet with a saddle to ride it.
Ridable: true
# If this is true, punching the creature with the bait will tame it, without hurting it. You can still use the right click method too. NOTE: This is inherently incompatible with Provokable: true.
AttackTame: false
# Distance from player that the pet will stop following and wander around a bit.
IdleDistance: 5
# Distance pets will check for entities to attack
AttackDistance: 10
# Allow ops to bypass permissions
OpsBypassPerms: false
# Maximum number of pets a player is allowed to have.
MaxPetsPerPlayer: 1
# If true aggressive and defensive pets can attack other players
PetsAttackPlayers: true
# If true aggressive and defensive pets can attack player pets
PetsAttackPets: true
# Don't change this
MainLoop: 1000
# Set to true if you don't use permissions
DisablePermissions: false
# Default pet mode (P = Passive, D = Defensive, A = Aggressive)
DefaultPetMode: P
# Change the command prefix. !!! You MUST edit the plugin.yml after changing this !!
CommandPrefix: pet
# This makes pets invincible
InvinciblePets: false