#Item IDs for bait for various monsters.
#You can't tame Skeletons and Ghasts, because they'll still shoot you.
#If you want to disable taming a certain mob, delete it or set the code
#to 0.
Blaze: 369
CaveSpider: 287
Chicken: 295
Cow: 295
Creeper: 318
EnderDragon: 122
Enderman: 122
Ghast: 370
Giant: 41
Golem: 265
MagmaCube: 378
MushroomCow: 40
Pig: 319
PigZombie: 319
Sheep: 338
Silverfish: 280
Slime: 341
SnowMan: 332
Spider: 287
Squid: 349
Golem: 265
Villager: 38
VillagerGolem: 265
Zombie: 288
#Other options
Provokable: true
Ridable: true
#If this is true, punching the creature with the bait will tame it, without hurting
#it. You can still use the right click method too. NOTE: This is inherently
#incompatible with Provokable: true.
AttackTame: false
#Distance from player that the pet will stop following
#and wander around a bit. Set it too low, and usually-hostile mob will hurt
#you.
IdleDistance: 5
# Allow ops to bypass permissions
OpsBypassPerms: false
MaxPetsPerPlayer: 1