name: PetCreeper
main: me.cnaude.plugin.PetCreeper.PetMain
version: 0.6a

commands:
    pet:
        description: Teleport your pet to you
        usage: /pet
        permission: petcreeper.pet
    petfree:
        description: Free your pet
        usage: /petfree
