name: PetCreeper
main: me.cnaude.plugin.PetCreeper.PetMain
version: 1.2.1
description: Tame those mobs!

commands:
    pet:
        description: Teleport your pet to you
        usage: /let [id|all]
    petfree:
        description: Free your pet
        usage: /petfree [id|all]
    petlist:
        description: List your pet type
        usage: /petlist
    petinfo:
        description: Display information about this pet
        usage: /petinfo [id]
    petname:
        description: Name your pet
        usage: /petname [id] [name]
    petgive:
        description: Give your pet to another player
        usage: /petgive [id] [player]
    petreload:
        description: Reload configuration
        usage: /petreload
    petmode:
        description: Change pet mode (aggressive, defensive, or passive)
        usage: /petmode [id] [a|d|p]
permissions:
  'petcreeper.*':
    description: Gives player access to all features of PetCreeper.
    default: false 
  petcreeper.reload:
    description: Allows players to use /petreload command.
    default: false 
  petcreeper.pet:
    description: Allows players to use /pet command.
    default: false
  petcreeper.give:
    description: Allows players to use /petgive command.
    default: false  
  petcreeper.mode:
    description: Allows players to use /petmode command.
    default: false  
  petcreeper.control:
    description: Allows players to control a pet while riding.
    default: false
  petcreeper.tame.Creeper:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Skeleton:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Spider:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Giant:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Zombie:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Slime:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Ghast:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.PigZombie:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Enderman:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.CaveSpider:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Silverfish:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Blaze:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.LavaSlime:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.EnderDragon:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Pig:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Sheep:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Cow:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Chicken:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Squid:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Wolf:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.MushroomCow:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.SnowMan:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.Villager:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.VillagerGolem:
    description: Allows players to tame this creature.
    default: false
  petcreeper.tame.All:
    description: Allows players to tame any creature.
    default: false
  petcreeper.ride.Creeper:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Skeleton:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Spider:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Giant:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Zombie:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Slime:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Ghast:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.PigZombie:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Enderman:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.CaveSpider:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Silverfish:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Blaze:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.LavaSlime:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.EnderDragon:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Pig:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Sheep:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Cow:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Chicken:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Squid:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Wolf:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.MushroomCow:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.SnowMan:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.Villager:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.VillagerGolem:
    description: Allows players to ride this creature.
    default: false
  petcreeper.ride.All:
    description: Allows players to ride any creature.
    default: false    
