name: PetCreeper
main: me.cnaude.plugin.PetCreeper.PetMain
version: 1.3.8-SNAPSHOT1
description: Tame those mobs!
author: Chris Naude
commands:
    pet:
        description: Teleport your pet to you
        usage: /let [id|all]
    petfree:
        description: Free your pet
        usage: /petfree [id|all]
    petlist:
        description: List your pet type
        usage: /petlist
    petinfo:
        description: Display information about this pet
        usage: /petinfo [id]
    petname:
        description: Name your pet
        usage: /petname [id] [name]
    petgive:
        description: Give your pet to another player
        usage: /petgive [id] [player]
    petreload:
        description: Reload configuration
        usage: /petreload
    petmode:
        description: Change pet mode (aggressive, defensive, or passive)
        usage: /petmode [id] [a|d|p]
    petage:
        description: Change pet's age (baby, adult, lock, unlock)
        usage: /petage [id] [baby|adult|lock|unlock]
    petspawn:
        description: Spawn a pet
        usage: /petspawn [creature type] [count]
permissions:
  'petcreeper.*':
    description: Gives player access to all features of PetCreeper.
    default: false 
  petcreeper.reload:
    description: Allows players to use /petreload command.
    default: false 
  petcreeper.pet:
    description: Allows players to use /pet command.
    default: false
  petcreeper.give:
    description: Allows players to use /petgive command.
    default: false  
  petcreeper.mode:
    description: Allows players to use /petmode command.
    default: false  
  petcreeper.age:
    description: Allows players to use /petage command.
    default: false 
  petcreeper.control:
    description: Allows players to control a pet while riding.
    default: false
  petcreeper.tame.All:
    description: Allows players to tame any creature.
    default: false
  petcreeper.ride.All:
    description: Allows players to ride any creature.
    default: false   
  petcreeper.spawn.All:
    description: Allows players to spawn any creature.
    default: false